import React, { Component } from 'react';
import Head from 'next/head';

const Page = ({ page }) => {
  //const { react: PageContent } = page;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <article className="prose">
          <h1>{page.title}</h1>
          {JSON.stringify(page)}
          {/* <ul>
            {cats.map((cat, k) => (
              <li key={k}>
                <h2>{cat.name}</h2>
                <p>{cat.description}</p>
              </li>
            ))}
          </ul> */}
        </article>
      </main>

      <footer></footer>
    </div>
  );
};

export const getStaticPaths = async () => {
  const paths = (context => {
    return context.keys().map(key => ({ params: { slug: key.replace(/^.*[\\\/]/, '').slice(0, -3) } }));
  })(require.context('../content/pages', true, /\.md$/));

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps = async context => {
  const { slug } = context.params;

  const page = await import(`../content/pages/${slug}.md`).catch(error => null);

  return {
    props: {
      //data: page,
      page: page.attributes,
    },
  };
};

export default Page;
