import Head from 'next/head';

import { attributes, react as HomeContent } from '../content/pages/home.md';

export default function Home() {
  let { title, cats } = attributes;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <article className="prose">
          <h1>{title}</h1>
          <HomeContent />
          <ul>
            {cats.map((cat, k) => (
              <li key={k}>
                <h2>{cat.name}</h2>
                <p>{cat.description}</p>
              </li>
            ))}
          </ul>
        </article>
      </main>

      <footer></footer>
    </div>
  );
}
